### ISSUE TITLE
Update website content

### ISSUE THREAD

**Issue by nas11ai** [Ouroboros-Tech/ouroboros-tech-website#14]
1. nama UKM
Ouroboros Technologies

2. logo UKM
ada di [drive assets ouroboros](https://drive.google.com/drive/u/1/folders/1SAjcOvYiYwtBz6GDoXVScQxtFf-Bx8zf)

3.tujuan UKM
Our vision is to make Institut Teknologi Kalimantan become the center for learning and development of information and communication technology in Balikpapan

4. projek dan deskripsinya
a. Internal Masterclass
We are committed to be ready for work industry, therefore we provide an intensive training program to develop our member skills and competencies.

b. The Boring Workshop
We want to share our knowledge that can help people to upgrade their skills in information and communication technology by providing certified workshops.

c. Technology Research and Development
We are committed to participate in the development of information and communication technology in Indonesia, especially in Balikpapan by releasing conducting related research and releasing related journals.

5. kata-kata di dalam website diganti pake bahasa inggris
beranda => home
 tentang => about us
anggota => our member
dokumentasi => documentation
kegiatan ukm => our program
dst.

**Comment by ersankarimi** [comment]
Oke otw ku update

**Comment by ersankarimi** [comment]
Sudah ku update sesuai yang diminta, jadi ku close
